version: '3.8'

services:
  # Spring Boot application
  springboot-app:
    image: crm-image:latest
    container_name: crm
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/crm?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    ports:
      - "9001:9001"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app-network

  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crm
    volumes:
      - ./sql/crm_initialize_database_20250227.sql:/docker-entrypoint-initdb.d/crm_initialize_database_20250227.sql
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  # RabbitMQ server
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ AMQP protocol
    networks:
      - app-network

# Volumes
volumes:
  mysql-data:

# Networks
networks:
  app-network:
    driver: bridge
